### ISSUE TITLE
Toggle Button Group - New Component

### ISSUE THREAD

**Issue by ArtBlue** [eBay/skin#2060] opened 2023-05-12 16:43 UTC
This introduces the `Toggle Button Group` that utilizes the atomic piece, `Toggle Button` component (#1970 ), to create a responsive layout.

Figma: https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/dzliniXCfXwfkNR4Eu40l5/eBay-Design-System?type=design&node-id=101602-121185&t=Uz1ynDZKKJyq6l26-0

Below is copied from dup issue...
Updated documentation for toggle button group.

Update name to “Toggle button group”
Added responsive layout section for guidance & clarity on max widths
Figma Link Here:
https://www.figma.com/file/zEBdEhbonrBOGzZ0fXzWvM/branch/dzliniXCfXwfkNR4Eu40l5/eBay-Design-System?type=design&node-id=101602%3A121185&t=oUa9vVc61zW1f7h3-1

**Comment by agliga** [comment] 2023-05-17 18:38
Duplicate of https://github.com/eBay/skin/issues/2059

**Comment by ArtBlue** [comment] 2023-05-23 14:41
As discussed during a meeting, I attempted to use `gap` for the margins around buttons. Unfortunately, we can't use `flex` with `gap` for the buttons because the resulting layout is something that design does not want. 
<img width="1590" alt="image" src="https://github.com/eBay/skin/assets/1675667/3c56d124-fe93-4768-8aa3-f14dd5094abb">

I'm reverting back to my initial implementation...

**Closed** 2023-07-24 17:10 UTC
Labels: type: feature, module: toggle-button-group
