### ISSUE TITLE
Infotip: overlay is obscured when placed inside of dialog

### ISSUE THREAD

**Issue by ianmcburnie** [eBay/skin#1424] opened 2021-04-29 23:13 UTC
We've seen this occur a few times when infotips and tooltips are inside of elements with hidden overflow. 

![Screen Shot 2021-04-29 at 12 05 55 PM](https://user-images.githubusercontent.com/38065/116629232-9edac480-a905-11eb-8c41-3d44fe121aa2.png)

**Comment by ArtBlue** [comment] 2023-08-10 18:12
I dug into this...

## The Problem

Because `.lightbox-dialog` has `position: fixed`, internal elements, even those with `position: absolute`, which is what `.infotip__overlay` is currently using, will not work (as evident in bug). The only way to allow the infotip to be displayed over the modal is to use `position: fixed`. However, simply making that positioning change will not work because it throws off the overlay positioning.

## The Solution Options

There are 3 solution options, one of which is a degraded fallback of infotips in modals:

1. Close this skin issue and start utilizing `popper.js` to handle the positioning in ebay ui. This would allow popper.js to handle all the use cases for positioning including this one to allow the infotip to display correctly. This approach would likely mean removing our own positioning logic in ebay ui.

2. In skin, add `position: fixed` to `infotip__overlay` to allow the infotip overlay to lift above the modal. Doing this in skin, however, will likely break the positioning math in ebay ui. The dev console change in skin looks like this:

<img width="520" alt="image" src="https://github.com/eBay/skin/assets/1675667/d2e170d5-6dfb-4a92-ac73-e1f754955705">

In ebay ui, a change the positioning logic/math will need to be made to work properly with the new positioning method. Additionally, this approach would require the ebay ui portion to be a concurrent change during the same release cycle.

3. The degraded fallback would be to turn the infotip display into an inline experience where the infotip does not lift off the page by using `position: relative` on the overlay (and hiding the pointer), and it will display like so only in modals:

<img width="505" alt="image" src="https://github.com/eBay/skin/assets/1675667/7dce39f1-4679-48e4-945f-5872773daa7f">

IMO, option 1 is preferable as it decouples the positioning/display portion from core functions and not just for this component, but for all components using overlays.

We've talked about using popper.js in other instances for other similar layout issues.

## Current Issue References

* https://github.com/eBay/ebayui-core/issues/535

**Comment by ArtBlue** [comment] 2023-08-10 18:41
@LuLaValva , oh yea, my comment had nothing to do with timing. I was merely grooming the backlog. This was just to prep the dev work for when we deem it a good time to do the work.

**Comment by ArtBlue** [comment] 2023-08-10 21:48
@ianmcburnie , I don't think the cascading solution (.panel-dialog .infotip__overlay { position: fixed }) would work. Ebay ui will "inherit" this and it will throw off the positions calcs.

As a precursor to the more bulletproof solution, I like the idea of using the new modifier method (`.infotip__overlay--fixed`) to solve the purely static issue. It has the benefit of not conflicting with the Ebay ui positioning calcs.

**Comment by ArtBlue** [comment] 2023-08-14 17:11
Ok, moving this out of the current release. We may want to dig into dialogs a bit more to see if position can be changed from `fixed` to `absolute` and also account for `overflow: hidden` since the issue is far more general than just infotips in modals.

**Comment by agliga** [comment] 2023-09-19 20:07
For this issue, lets try to see to get popper support both on skin and ebayui.

**Closed** 2023-12-22 22:58 UTC
Labels: module: dialog, status: backlog, module: infotip
