### ISSUE TITLE
Radio button on IE11 gets cut off on 125% zoom

### ISSUE THREAD

**Issue by BhavinPatel04** [eBay/skin#877] opened 2019-10-09 16:57 UTC
![Screen Shot 2019-10-08 at 11 37 19 AM](https://user-images.githubusercontent.com/6559211/66502936-1b375980-ea7b-11e9-81cd-d6fe9856b14a.png)

**Comment by ianmcburnie** [comment] 2019-10-09 17:17
Thanks for catching this @BhavinPatel04 

We have however decided that we will no longer be fixing fit & finish issues such as this in IE11. If the radio button was completely obscured we might reconsider.

**Comment by HenriqueLimas** [comment] 2020-04-14 21:05
Hi @ianmcburnie, we have an issue where the radio button is completely obscured and cutted:

### IE 11 issue
<img width="617" alt="ie-error" src="https://user-images.githubusercontent.com/2222191/79273950-a34a5180-7e58-11ea-817a-4944671d10f6.png">

### Chrome (Expected layout)
<img width="487" alt="chrome" src="https://user-images.githubusercontent.com/2222191/79273943-a1808e00-7e58-11ea-9c36-b0b84e28970c.png">

It seems that the issue is how IE calculates the flexbox size and don't respect the `width` properly. Using a `min-width`  together with the `width` should solve the problem.

**Comment by ianmcburnie** [comment] 2020-04-14 21:25
Thanks @HenriqueLimas. Reopening so we can take a look.

**Comment by ianmcburnie** [comment] 2020-04-14 23:31
@HenriqueLimas I'm unable to reproduce in IE11. Can you perhaps share your code or create a quick test case? I have a couple of other possible solutions too, but need to be able to reproduce it first.

**Comment by ianmcburnie** [comment] 2020-04-15 15:57
Fixed in 9.x and 10.x

**Closed by ianmcburnie** 2020-04-15 15:57 UTC
Labels: aspect: IE11, aspect: red-lines, status: investigate, workaround: yes
