### ISSUE TITLE
listbox-button: listbox option text is truncated to width of button

### ISSUE THREAD

**Issue by LuLaValva** [eBay/skin#2214] opened 2023-11-21 22:50 UTC
### I verified there's no existing issue for this bug.

- [X] There are no existing issues

### Current behavior

[Font Size story](https://opensource.ebay.com/skin/storybook/?path=/story/skin-listbox-button-cascade--font-size) shows truncated text.

<img width="158" alt="image" src="https://github.com/eBay/skin/assets/26027232/7128be37-dfca-4268-8f41-5a0d9e91a7f0">

### Expected behavior

Text should not be truncated.

![image](https://github.com/eBay/skin/assets/26027232/cf06f969-268b-41ea-9df7-52285e7621a9)

### Skin version

16.9.0

### Device/OS/Browser info

MacOS, Google Chrome

### Steps to reproduce

```bash
Visit [font size story](https://opensource.ebay.com/skin/storybook/?path=/story/skin-listbox-button-cascade--font-size)
```

**Comment by ArtBlue** [comment] 2023-12-11 14:47
I'm not convinced this is a bug. Here's the web archive for listbox from 2022 that clearly shows we've had the ellipses: 

<img width="1393" alt="image" src="https://github.com/eBay/skin/assets/1675667/bbf3795a-4d8f-4109-8b4e-f92d13ea57c3">

For this to be considered a true bug, we would have to have the specifications clearly showing something clearly different from implementation from the time period before the implementation happened.

Design may simply not have considered this use case.

We do have an agenda item with design to revisit ellipses usage - either eliminate or reduce, but even that change would be a feature change, not a bug.

**Comment by agliga** [comment] 2023-12-12 17:57
Fixed by duplicate bug https://github.com/eBay/skin/issues/2228

**Closed by agliga** 2023-12-12 17:57 UTC
Labels: type: bug
