### ISSUE TITLE
using floating-label in ebay-textbox adds margin-top: 14px

### ISSUE THREAD

**Issue by BhavinPatel04** [eBay/skin#1481] opened 2021-06-21 21:13 UTC
using floating label in ebay-textbox adds margin-top: 14px
![image](https://user-images.githubusercontent.com/6559211/122828567-d9ccf900-d2b3-11eb-8c19-fba2cb597264.png)

**Comment by austingardner** [comment] 2021-06-22 06:13
I'm not quite understanding what the issue is here. The example with `floatin-label--large` and `textbox__control--large` has `margin-top: 14px` already.

**Comment by BhavinPatel04** [comment] 2021-06-22 16:06
Yeah, it shouldn't have `margin-top: 14px`.

**Comment by ianmcburnie** [comment] 2021-06-22 16:42
Hm, this margin-top is possibly a leftover from the previous incarnation of floating-label that floated above the textbox. @agliga?

**Comment by austingardner** [comment] 2021-06-29 15:22
Had to revert the fix, caused issues with ebay-ui. We will have to look into this more

**Comment by ianmcburnie** [comment] 2021-07-14 19:50
This is fixed in 12.x

**Closed by ianmcburnie** 2021-07-14 19:50 UTC
Labels: module: floating-label, resolution: fixed
