### ISSUE TITLE
infotip: DS4 - cart icon is smaller and lighter

### ISSUE THREAD

**Issue by hramakumar** [eBay/skin#757] opened 2019-08-13 23:15 UTC
skin 9.0.0-0
ebayui - 3.0.0-4

the cart icon in info tip has got a lot smaller and lighter.
I am comparing the cart Icon we currently have with older skin version with 9.0.0-0
https://www.loom.com/share/d1bebefa221c4368b1da8595cc43413f

**Comment by msendlakowski** [comment] 2019-08-14 21:12
This is the expected behavior based on this PR:
https://github.com/eBay/skin/pull/750

Which was a fix for this bug:
https://github.com/eBay/ebayui-core/issues/823

If you look in the old test you can see that the icon was outside of the 16px button area.
![Screen Shot 2019-08-14 at 2 07 27 PM](https://user-images.githubusercontent.com/1562843/63056456-f5d40800-be9c-11e9-8b5c-0bac7c43f0bc.png)

This fix makes sure the icon is within the proper area, but means it will resize itself.

Since the design team is giving us some smaller icons, we _should_ be able to fix this when we update the icons for the DS 6.5 update in https://github.com/eBay/skin/issues/699

For now, I'll put this in the backlog.

**Comment by msendlakowski** [comment] 2019-08-15 17:46
@agliga We probably just have to update the infotip documentation to recommend the small icons, once they are available.

**Comment by ianmcburnie** [comment] 2019-08-17 07:30
Small icons? So are we doing something like `icon--small`?

**Comment by msendlakowski** [comment] 2019-08-21 17:14
@ianmcburnie - Sorry I missed this comment. Yes, the design team is creating some modified "small" icons because some of the default icons don't resize very well on their own.

So we'll have `cart` and `cart-small` CSS classes in skin.  So @agliga should be able to resolve this by using the `cart-small` icon.

**Comment by ianmcburnie** [comment] 2019-08-22 19:01
Hmm, we are not keeping `icon icon--cart`? That would be a big change.

**Comment by seangates** [comment] 2019-08-22 19:30
I read that as @msendlakowski implying `icon icon--cart` and `icon icon--cart-small`.

**Comment by msendlakowski** [comment] 2019-08-22 19:36
@ianmcburnie @seangates Yes, sorry for the confusion.  The only difference should be that we're adding small icons to the existing list.  So we'll make the following available:
`icon icon--cart` 
`icon icon--cart-small` (with its own dimensions)

**Comment by agliga** [comment] 2019-08-30 18:54
This is not an issue with skin, but rather the test pages. In skin there are no examples with cart in infotip

**Closed** 2019-09-03 23:49 UTC
Labels: module: SVG, module: icon, regression: no, status: closed, type: bug
