### ISSUE TITLE
Fix Icons and Match DS

### ISSUE THREAD

**Issue by ArtBlue** [eBay/skin#1998] opened 2023-03-02 17:26 UTC
With the new set of icons introduced in `15.5.0`, DS also created new and more complex icons with a `-colored` postfix. Those icons are currently not displaying the way they were designed because of the overarching styles that are applied to the way we treat icons in Skin.

Additionally, the introduction of `svg` widths caused breaks in certain implementations (i.e. textbox).

### Remove SVG Widths
1. Add a process in the image processing script to remove widths and heights from `svg` files.

### Examples of the Complex Icon Issue

**Light Mode**
<img width="118" alt="image" src="https://user-images.githubusercontent.com/1675667/222507024-f9b3b187-6f1b-41a0-948b-82f8d7db65ed.png">
(border stroke missing)

**Dark Mode**
<img width="117" alt="image" src="https://user-images.githubusercontent.com/1675667/222506699-afc16152-bd13-4616-b3b4-b790f570531a.png">

For this issue, we need to work in conjunction with DS to both - 

1. Find the optimal structure for these complex icons.
2. Have DS recreate the complex icons with the optimal structure.
3. Possibly tweak some styles in Skin to accommodate the complex icons.

Number 3 above may or may not be necessary depending on the final structure of the complex icons.

**Comment by ratinsl** [comment] 2023-03-03 04:46
Hey @ArtBlue , here is a package with only the files that need to be updated to help fix this issue. Please let me know if you see any issues. I left the width/heights in so you can run your script to remove them.
[230302_Skin_Icon_-colored_fixes.zip](https://github.com/eBay/skin/files/10878257/230302_Skin_Icon_-colored_fixes.zip)

**Comment by ratinsl** [comment] 2023-03-03 04:48
Also, I noticed there was a duplicate of the escrow card. You can remove the (4) labeled "escrow-#-colored". The correct name to use is "escrow-card-#-colored" which
<img width="1069" alt="Screen Shot 2023-03-02 at 7 41 18 PM" src="https://user-images.githubusercontent.com/33495986/222633905-cf00a105-e0c4-43ef-bc87-8abdd0762d26.png">
 is in the package attached above.

**Closed** 2023-03-03 18:30 UTC
Labels: module: icon, priority: 2
