### ISSUE TITLE
button.fake-link: font size should be inherited rather than hard-coded to .875rem

### ISSUE THREAD

**Issue by melquan** [eBay/skin#1227] opened 2020-08-31 16:00 UTC
The font size for a `fake-link` button is set to `.875rem` but if the surrounding text is smaller, in the case of legal text for example, the links are larger than the surrounding text.

![image](https://user-images.githubusercontent.com/19419138/91740585-5d242f00-eb68-11ea-8038-811a3d8195fd.png)

It should be the same font size as the surrounding text.

**Comment by ianmcburnie** [comment] 2020-08-31 16:59
We fixed this in 11.0.0:

https://github.com/eBay/skin/issues/1187

Let me know if you need it in an earlier version too.

**Comment by melquan** [comment] 2020-08-31 17:04
I can override this in our app until then but it would be nice to have it in 10.x.x.

**Comment by ianmcburnie** [comment] 2020-09-01 16:18
Oh, actually the reason we didn't put it in 10.x is because I thought it could technically lead to a breaking change or unexpected results. 

https://github.com/eBay/skin/issues/1187#issuecomment-665276848

I think perhaps if you can just override for now, and then pick it up in v11 when the time comes.

**Comment by ianmcburnie** [comment] 2020-09-01 19:16
Closing as duplicate of #1187

**Closed** 2020-09-01 19:16 UTC
Labels: module: link
