### ISSUE TITLE
Menu: Label sits few pixels down in IE

### ISSUE THREAD

**Issue by PrashantAshok** [eBay/skin#319] opened 2018-08-17 21:49 UTC
Environment:
- **Browser**: IE11
- **Skin version**: 5.1.2

In IE 11, the label is placed few pixels down compared to chrome. 

Chrome: 
![screen shot 2018-08-17 at 2 44 45 pm](https://user-images.githubusercontent.com/5200733/44290175-5bf76200-a22c-11e8-840f-5dca89a370b4.png)

IE: 
<img width="249" alt="screen shot 2018-08-17 at 2 44 38 pm" src="https://user-images.githubusercontent.com/5200733/44290184-61ed4300-a22c-11e8-812f-aeb2b5bec40c.png">

Reproducible in http://ebay.github.io/skin/ds6/#menu

Related Note: `initial` isn't supported in IE 11. https://github.com/eBay/skin/blob/6.0.0/src/less/dropdown/base/dropdown.less#L21

**Comment by PrashantAshok** [comment] 2018-08-25 22:05
Apologies, here is the [demo](https://s.codepen.io/aprashant_jsr/debug/oPbddj/PBkNWNnyGJNM). 
Skin: 5.1.2 (same as that of the `gh` pages)

It seems to be work fine in `v6.0.0-2`

**Comment by msendlakowski** [comment] 2018-08-29 00:04
Confirmed with Prashant, close it for now since its fixed in v6.  They will try to wait and pick up the fix then.

**Closed by msendlakowski** 2018-08-29 00:04 UTC
Labels: design system: DS6, good first issue, module: menu, status: to do
