### ISSUE TITLE
Badge: button badge clipped in IE11

### ISSUE THREAD

**Issue by seangates** [eBay/skin#587] opened 2019-03-15 05:48 UTC
The icon button badge is clipped on IE11. The simple fix is to add a `overflow: visible` to the button.

### Before
![image](https://user-images.githubusercontent.com/105656/54411041-8373b780-46b3-11e9-8ff7-214edbfcd31c.png)

### After
![image](https://user-images.githubusercontent.com/105656/54411057-91c1d380-46b3-11e9-8b6f-36a48f69eeb5.png)

**Comment by ianmcburnie** [comment] 2019-06-14 23:56
Closing as duplicate of #640.

**Closed by ianmcburnie** 2019-06-14 23:56 UTC
Labels: aspect: IE11, good first issue, module: badge, priority: 4, resolution: duplicate, type: bug
